FROM ghcr.io/astral-sh/uv:python3.13-bookworm

ARG USER=aprendo
ARG TINI_VERSION=v0.19.0

ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini


RUN useradd -ms /bin/bash $USER \
    && chown -R $USER:$USER /home/$USER

USER $USER
WORKDIR /home/$USER
COPY ./app/pyproject.toml /home/$USER/

RUN uv venv \
    && uv sync --no-dev --no-install-project

ENV PATH="/home/$USER/.venv/bin:$PATH"

ENTRYPOINT ["/tini", "--"]
CMD ["/bin/bash"]

USER 0
