FROM aprendo-venv AS builder

WORKDIR /app

COPY ./app/rxconfig.py /app/
COPY ./app/aprendo /app/aprendo

RUN reflex export --frontend-only --no-zip

FROM nginx

COPY --from=builder /app/.web/_static /usr/share/nginx/html
COPY ./deployment/nginx.conf /etc/nginx/conf.d/default.conf
